# Generated by Django 4.1 on 2023-02-11 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
