# Generated by Django 4.1 on 2023-02-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_downvotes_post_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='posts',
            field=models.ManyToManyField(to='api.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='account_poster',
            field=models.CharField(default='', max_length=151),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('V', 'Vegan'), ('M', 'Meat'), ('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
