# Generated by Django 4.1 on 2023-03-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='food',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
