# Generated by Django 4.1 on 2023-03-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='account_poster',
            field=models.CharField(max_length=151),
        ),
    ]
