# Generated by Django 4.1 on 2023-06-27 23:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_tag_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='account_id',
            field=models.CharField(default=api.models.generate_unique_id, max_length=15),
        ),
    ]
