# Generated by Django 4.1 on 2023-07-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_account_id_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='downvoted_posts',
            field=models.ManyToManyField(related_name='downvoted_posts', to='api.post'),
        ),
        migrations.AddField(
            model_name='account',
            name='upvoted_posts',
            field=models.ManyToManyField(related_name='upvoted_posts', to='api.post'),
        ),
        migrations.AlterField(
            model_name='account',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='api.post'),
        ),
    ]
