# Generated by Django 4.1 on 2023-07-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location_lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='location_long',
            field=models.IntegerField(default=0),
        ),
    ]
