# Generated by Django 4.1 on 2023-12-13 03:40

from django.db import migrations

def delete_posts(apps, schema_editor):
    Post = apps.get_model('your_app_name', 'Post')
    Post.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_post_location_lat_post_location_long'),
    ]

    operations = [
        migrations.RunPython(delete_posts),
    ]
