# Generated by Django 5.0.1 on 2024-02-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20231212_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='food_left',
            field=models.IntegerField(default=10),
        ),
    ]
